name: Build

on:
  push:
    branches:
#      - master
      - develop
  pull_request:
    branches:
#      - master
      - develop

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Test
        if: env.BRANCH_NAME == 'develop'
        run: |
          docker tag ${IMAGE}${IMAGE_POSTFIX}:${TAG} ${IMAGE}${IMAGE_POSTFIX}:latest
          docker tag ${IMAGE}${IMAGE_POSTFIX}:${TAG} ${IMAGE}${IMAGE_POSTFIX}:${GITHUB_SHA}
          docker push ${IMAGE}${IMAGE_POSTFIX}:latest
          docker push ${IMAGE}${IMAGE_POSTFIX}:${GITHUB_SHA}
